function out1 = jointjacibian_3(in1,in2)
%JOINTJACIBIAN_3
%    OUT1 = JOINTJACIBIAN_3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-May-2020 10:56:21

obx = in2(1,:);
oby = in2(2,:);
obz = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = sin(q2);
t8 = t2.*t3.*(1.0./5.0);
t4 = oby-t8;
t5 = sin(q1);
t10 = t3.*t5.*(1.0./5.0);
t6 = obz-t10;
t12 = cos(q2);
t13 = t12.*(1.0./5.0);
t14 = -obx+t13+1.7e1./5.0e1;
t7 = abs(t14);
t9 = abs(t4);
t11 = abs(t6);
t15 = sign(t4);
t16 = sign(t6);
t17 = t7.^2;
t18 = t9.^2;
t19 = t11.^2;
t20 = t17+t18+t19;
t21 = 1.0./sqrt(t20);
out1 = [t21.*(t2.*t3.*t11.*t16.*(2.0./5.0)-t3.*t5.*t9.*t15.*(2.0./5.0)).*(-1.0./2.0),t21.*(t3.*t7.*sign(t14).*(2.0./5.0)+t2.*t9.*t12.*t15.*(2.0./5.0)+t5.*t11.*t12.*t16.*(2.0./5.0)).*(-1.0./2.0),0.0,0.0,0.0,0.0,0.0];
