function qdz = qdotangle(in1)
%QDOTANGLE
%    QDZ = QDOTANGLE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-May-2020 10:56:26

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
t2 = 1.0./pi;
t3 = pi.*(1.7e1./1.8e1);
t4 = pi.*(2.0./3.0);
qdz = [t2.*(t3+t2.*x1.*(1.8e1./1.7e1)).*(-1.8e1./1.19e2);t2.*(t4+t2.*x2.*(3.0./2.0)).*(-3.0./1.4e1);t2.*(t3+t2.*x3.*(1.8e1./1.7e1)).*(-1.8e1./1.19e2);t2.*(t4+t2.*x4.*(3.0./2.0)).*(-3.0./1.4e1);t2.*(t3+t2.*x5.*(1.8e1./1.7e1)).*(-1.8e1./1.19e2);t2.*(t4+t2.*x6.*(3.0./2.0)).*(-3.0./1.4e1);t2.*(pi.*(3.5e1./3.6e1)+t2.*x7.*(3.6e1./3.5e1)).*(-3.6e1./2.45e2)];
